---
- name: mongodb tasks
  hosts: all
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ name }}"
    loop:
    - update-apt-sources-1.0.0
    - disable-apt-jobs-1.0.0
    - disable-motd-1.0.0
    - app-agent-1.1.1
    - appctl-1.2.7
    - mongodb-common
    loop_control:
      loop_var: name